name: open_ai_simplified
description: OpenAI Simplified is an application that aims to provide easy and intuitive access to OpenAI services. 
version: 0.0.3
homepage: "https://github.com/DuvCabrera/open-ai-simplified"

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  provider: ^6.0.5
  dio: ">=4.0.6 <5.0.0"
  http_parser: ^4.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.3.2

flutter:
